/** @doc Privacy policy — how Megsy collects, stores and protects personal data. */
import LegalPageLayout, { type LegalSection } from "@/components/landing/LegalPageLayout";

const sections: LegalSection[] = [
  {
    heading: "Who We Are",
    paragraphs: [
      "Megsy for Digital Platforms & E-Commerce Development LLC (Commercial Registry 248691, Tax ID 774034785), incorporated in the Arab Republic of Egypt, is the data controller for personal data processed through the Megsy AI platform.",
      "This Privacy Policy explains what personal data we collect, why we collect it, how we use and protect it, and the rights you have over your data.",
    ],
  },
  {
    heading: "Data We Collect",
    paragraphs: [
      "We collect data you provide directly, data generated by your use of the Service, and data from third parties when you use a sign-in provider or payment processor.",
    ],
    list: [
      "Account data: name, email, display name, profile photo, authentication identifiers.",
      "Workspace data: workspace name, team member roles, billing contact.",
      "Content data: prompts, uploaded files, generated outputs, project files, conversations.",
      "Usage data: pages visited, features used, credit consumption, device and browser type, IP address, approximate location derived from IP.",
      "Billing data: plan, subscription status, last four digits of payment method, transaction history. Full card numbers are processed by our payment provider and never stored by Megsy.",
    ],
  },
  {
    heading: "How We Use Your Data",
    paragraphs: [
      "We use personal data to provide, secure and improve the Service, to communicate with you, and to comply with legal obligations.",
    ],
    list: [
      "Operate the Service: authenticate you, route generation requests to model providers, store your projects, deliver outputs.",
      "Billing: process subscriptions and credit purchases, prevent fraud, issue invoices.",
      "Security: detect abuse, enforce the Acceptable Use Policy, investigate incidents.",
      "Improvement: aggregate, anonymised analytics to understand which features work and where to invest.",
      "Communication: send transactional emails, security alerts, and (where you consent) product updates.",
      "Legal: comply with tax, accounting, anti-money-laundering, and lawful-request obligations.",
    ],
  },
  {
    heading: "Legal Bases",
    paragraphs: [
      "Where the GDPR or analogous laws apply, we rely on the following legal bases: performance of a contract with you (to deliver the Service), our legitimate interests (to secure and improve the Service), your consent (for optional analytics, marketing, and certain cookies) and legal obligations (tax, accounting, lawful requests).",
    ],
  },
  {
    heading: "Sharing & Sub-Processors",
    paragraphs: [
      "We do not sell personal data. We share limited data with vetted sub-processors who help us run the Service, under strict data-processing agreements.",
    ],
    list: [
      "Cloud hosting and database providers that store your account and project data.",
      "AI model providers that process the prompts and inputs you submit to generate outputs.",
      "Payment processors that handle subscriptions and credit purchases.",
      "Email and notification providers that deliver transactional messages.",
      "Analytics and error-monitoring providers (only with your consent for non-essential analytics).",
    ],
  },
  {
    heading: "International Transfers",
    paragraphs: [
      "Megsy operates globally. Your data may be processed in countries outside Egypt or the European Economic Area. Where required, we use approved transfer mechanisms such as Standard Contractual Clauses to safeguard your data.",
    ],
  },
  {
    heading: "Retention",
    paragraphs: [
      "We keep personal data only for as long as necessary to provide the Service, comply with legal obligations, resolve disputes, and enforce our agreements.",
      "Account data is retained while your account is active and for up to 24 months after closure, after which it is deleted or fully anonymised, except where longer retention is required by law (e.g. tax records).",
      "Generated outputs and uploaded files are kept while you keep them in your account; deleting a conversation, project, or asset removes it from active systems within 30 days and from backups within 90 days.",
    ],
  },
  {
    heading: "Your Rights",
    paragraphs: [
      "Subject to applicable law, you have the right to access, correct, delete, restrict, or object to processing of your personal data, the right to data portability, and the right to withdraw consent at any time.",
    ],
    list: [
      "Access: request a copy of the personal data we hold about you.",
      "Correction: ask us to fix inaccurate or incomplete data.",
      "Deletion: request that we delete your data, subject to legal retention obligations.",
      "Portability: receive a machine-readable export of your data.",
      "Objection: object to processing based on our legitimate interests.",
      "Complaint: lodge a complaint with your local data-protection authority.",
    ],
  },
  {
    heading: "Children",
    paragraphs: [
      "The Service is not directed to anyone under 18. We do not knowingly collect personal data from minors. If you believe we have, contact us and we will delete it.",
    ],
  },
  {
    heading: "Security",
    paragraphs: [
      "We implement technical and organisational measures to protect your data, including encryption in transit and at rest, row-level access control, scoped service tokens, audit logging, and routine security reviews. No system is perfectly secure; we encourage you to enable two-factor authentication and use a strong, unique password.",
    ],
  },
  {
    heading: "Cookies",
    paragraphs: [
      "We use cookies and similar technologies as described in our Cookie Policy. Essential cookies are required for the Service to function; you can manage non-essential cookies at any time.",
    ],
  },
  {
    heading: "Changes to This Policy",
    paragraphs: [
      "We may update this Privacy Policy from time to time. Material changes will be announced in-app or by email at least 14 days before they take effect.",
    ],
  },
  {
    heading: "California Privacy Rights (CCPA / CPRA)",
    paragraphs: [
      'California residents have the right to know what personal information we collect, to access and receive a copy of it, to correct inaccuracies, to delete it, and to limit use of sensitive personal information. You also have the right to opt out of "sale" or "sharing" of personal information.',
      "Megsy does NOT sell personal information and does NOT share personal information for cross-context behavioural advertising. We honour Global Privacy Control (GPC) signals as a valid opt-out. To exercise any right, email privacy@megsyai.com — we verify identity via the email on file and respond within 45 days.",
    ],
  },
  {
    heading: "Other US-State Privacy Rights",
    paragraphs: [
      "Residents of Virginia (VCDPA), Colorado (CPA), Connecticut (CTDPA), Utah (UCPA), Texas (TDPSA), Oregon, Montana, and other states with comprehensive privacy laws have substantially equivalent rights — confirmation, access, correction, deletion, portability, and opt-out of targeted advertising, sale, and profiling. Submit requests to privacy@megsyai.com.",
    ],
  },
  {
    heading: "Brazil LGPD",
    paragraphs: [
      "Under Lei Geral de Proteção de Dados (Law 13.709/2018), Brazilian data subjects have the rights set out in Articles 17–22: confirmation, access, correction, anonymisation, blocking or deletion of unnecessary data, portability, information about sharing, information about consequences of refusing consent, and revocation of consent. Requests to privacy@megsyai.com.",
    ],
  },
  {
    heading: "Children's Privacy (COPPA)",
    paragraphs: [
      "Megsy is intended for adults (18+) and is not directed to children. We do not knowingly collect personal information from anyone under 13 (US COPPA threshold) or under 18 (our platform requirement). If we discover an underage account, we terminate it and delete associated data. Parents and guardians may contact privacy@megsyai.com for immediate removal.",
    ],
  },
  {
    heading: "Egypt PDP Law & MENA",
    paragraphs: [
      "As an Egyptian-incorporated entity, Megsy complies with the Egyptian Personal Data Protection Law 151/2020. Equivalent rights are extended to residents of Saudi Arabia (PDPL), the UAE (PDPL Federal Decree 45/2021), and other MENA jurisdictions where comprehensive data-protection law applies.",
    ],
  },
  {
    heading: "Contact & Data Requests",
    paragraphs: [
      'To exercise any of your rights or to ask a privacy question, write to privacy@megsyai.com (or support@megsyai.com) with the subject "Privacy Request." We verify identity via the account email and respond within 30 days (45 days for CCPA, 15 days for LGPD where feasible).',
    ],
  },
];

const PrivacyPage = () => (
  <LegalPageLayout
    eyebrow="Legal"
    title="Privacy Policy"
    subtitle="What we collect, why we collect it, and the controls you have over your personal data on Megsy AI."
    lastUpdated="19 May 2026"
    sections={sections}
    seoTitle="Privacy Policy"
    seoDescription="Learn how Megsy AI collects, uses, shares, and protects your personal data, and the rights you have over it."
    canonicalPath="/privacy"
    heroVariant="team"
  />
);

export default PrivacyPage;
